//! # codex-types — Thin Leaf Types for Cortex
//!
//! Shared event types consumed by 5+ crates. No internal dependencies.
//! Exists to keep the workspace dependency graph clean.
//!
//! Corey's answer: "Five consumers across five crates. Thin leaf crate —
//! no dependencies beyond serde and maybe chrono."

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// ── MindEvent — the unified event type ──────────────────────────────────────

/// Every event that flows through the coordination engine.
///
/// External events come from outside (Hub, Telegram, Human, sub-mind results).
/// Drive events come from DriveLoop (idle detection, task discovery).
///
/// The EventBus dispatches these with biased priority: external first, drive second.
/// This ensures real work always preempts self-prompted activity.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum MindEvent {
    /// External input from any source.
    External(ExternalEvent),
    /// Self-prompted event from DriveLoop.
    Drive(DriveEvent),
}

/// An event from an external source.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExternalEvent {
    pub source: EventSource,
    pub content: String,
    pub priority: EventPriority,
    pub timestamp: DateTime<Utc>,
    #[serde(default)]
    pub metadata: serde_json::Value,
}

/// Source of an external event.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EventSource {
    Hub { room: String, thread: Option<String> },
    Telegram { chat_id: String },
    Boop { boop_type: String },
    SubMindResult { mind_id: String, task_id: String },
    Human { name: String },
    Schedule { trigger_name: String },
    Ipc { sender: String },
}

/// Priority of an event. Ordered lowest to highest.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EventPriority {
    /// Background noise. Handle if idle.
    Low,
    /// Standard work item.
    Normal,
    /// Should be handled soon.
    High,
    /// Requires immediate attention.
    Critical,
}

// ── DriveEvent — self-prompted events from the DriveLoop ────────────────────

/// Events generated by the DriveLoop when the mind is idle.
///
/// Four types, ordered by priority (highest first):
/// 1. TaskAvailable — a task in the queue is ready
/// 2. StallDetected — a delegated task hasn't reported back
/// 3. IdleSuggestion — nothing urgent, but here's something productive
/// 4. HealthCheck — periodic self-diagnostic
///
/// Priority ordering is enforced by EventPriority, not by enum order.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "drive_type", rename_all = "snake_case")]
pub enum DriveEvent {
    /// A task in the TaskStore is ready to be worked on.
    TaskAvailable {
        task_id: String,
        description: String,
        priority: EventPriority,
    },
    /// A delegated task hasn't reported back within the stall threshold.
    StallDetected {
        task_id: String,
        mind_id: String,
        stalled_seconds: u64,
    },
    /// Nothing urgent — suggest productive activity based on role.
    IdleSuggestion {
        suggestion: String,
    },
    /// Periodic self-diagnostic.
    HealthCheck {
        active_minds: u32,
        pending_tasks: u32,
        uptime_seconds: u64,
    },
}

impl DriveEvent {
    /// Generate a role-appropriate prompt for this drive event.
    ///
    /// REQ-6: Drive event prompts enforce A3 role boundaries.
    /// "DO NOT execute directly" is hard-coded for Primary and TeamLead.
    pub fn prompt(&self, role_str: &str) -> String {
        let delegation_guard = match role_str {
            "primary" | "team_lead" => "\n\nDO NOT execute directly. Delegate to the appropriate team lead or agent.",
            _ => "",
        };

        let base = match self {
            DriveEvent::TaskAvailable { task_id, description, priority } => {
                format!(
                    "[DRIVE] Task ready: {task_id} ({priority:?})\n\
                     Description: {description}\n\
                     Action: Pick up this task or delegate it."
                )
            }
            DriveEvent::StallDetected { task_id, mind_id, stalled_seconds } => {
                format!(
                    "[DRIVE] Stall detected: task {task_id} assigned to {mind_id} \
                     has not reported in {stalled_seconds}s.\n\
                     Action: Check status, reassign, or escalate."
                )
            }
            DriveEvent::IdleSuggestion { suggestion } => {
                format!(
                    "[DRIVE] Idle. Suggestion: {suggestion}"
                )
            }
            DriveEvent::HealthCheck { active_minds, pending_tasks, uptime_seconds } => {
                format!(
                    "[DRIVE] Health: {active_minds} minds active, \
                     {pending_tasks} tasks pending, uptime {uptime_seconds}s."
                )
            }
        };

        format!("{base}{delegation_guard}")
    }

    /// Priority of this drive event for routing decisions.
    pub fn priority(&self) -> EventPriority {
        match self {
            DriveEvent::TaskAvailable { priority, .. } => *priority,
            DriveEvent::StallDetected { .. } => EventPriority::High,
            DriveEvent::IdleSuggestion { .. } => EventPriority::Low,
            DriveEvent::HealthCheck { .. } => EventPriority::Low,
        }
    }

    /// Whether this event should reach Primary's conscious context.
    ///
    /// 90% autonomic: most drive events route to ops-lead.
    /// Only stall_detected and critical task_available reach Primary.
    pub fn reaches_primary(&self) -> bool {
        match self {
            DriveEvent::StallDetected { .. } => true,
            DriveEvent::TaskAvailable { priority, .. } => *priority >= EventPriority::Critical,
            _ => false,
        }
    }
}

impl MindEvent {
    /// Overall priority of this event.
    pub fn priority(&self) -> EventPriority {
        match self {
            MindEvent::External(e) => e.priority,
            MindEvent::Drive(d) => d.priority(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn drive_event_prompt_primary_has_guard() {
        let event = DriveEvent::IdleSuggestion {
            suggestion: "Review pending tasks".into(),
        };
        let prompt = event.prompt("primary");
        assert!(prompt.contains("DO NOT execute directly"));
    }

    #[test]
    fn drive_event_prompt_agent_no_guard() {
        let event = DriveEvent::IdleSuggestion {
            suggestion: "Clean up temp files".into(),
        };
        let prompt = event.prompt("agent");
        assert!(!prompt.contains("DO NOT execute directly"));
    }

    #[test]
    fn stall_reaches_primary() {
        let event = DriveEvent::StallDetected {
            task_id: "t-001".into(),
            mind_id: "research-lead".into(),
            stalled_seconds: 300,
        };
        assert!(event.reaches_primary());
    }

    #[test]
    fn idle_does_not_reach_primary() {
        let event = DriveEvent::IdleSuggestion {
            suggestion: "Check memory".into(),
        };
        assert!(!event.reaches_primary());
    }

    #[test]
    fn critical_task_reaches_primary() {
        let event = DriveEvent::TaskAvailable {
            task_id: "t-urgent".into(),
            description: "Critical fix needed".into(),
            priority: EventPriority::Critical,
        };
        assert!(event.reaches_primary());
    }

    #[test]
    fn normal_task_does_not_reach_primary() {
        let event = DriveEvent::TaskAvailable {
            task_id: "t-routine".into(),
            description: "Routine work".into(),
            priority: EventPriority::Normal,
        };
        assert!(!event.reaches_primary());
    }

    #[test]
    fn mind_event_priority() {
        let ext = MindEvent::External(ExternalEvent {
            source: EventSource::Human { name: "Corey".into() },
            content: "test".into(),
            priority: EventPriority::Critical,
            timestamp: Utc::now(),
            metadata: serde_json::Value::Null,
        });
        assert_eq!(ext.priority(), EventPriority::Critical);

        let drv = MindEvent::Drive(DriveEvent::HealthCheck {
            active_minds: 3,
            pending_tasks: 0,
            uptime_seconds: 600,
        });
        assert_eq!(drv.priority(), EventPriority::Low);
    }

    #[test]
    fn serialization_roundtrip() {
        let event = MindEvent::Drive(DriveEvent::TaskAvailable {
            task_id: "t-001".into(),
            description: "Build something".into(),
            priority: EventPriority::High,
        });
        let json = serde_json::to_string(&event).unwrap();
        let parsed: MindEvent = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.priority(), EventPriority::High);
    }
}
